apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: OpenSearch Logs
    type: grafana-opensearch-datasource
    uid: opensearch-logs
    access: proxy
    url: http://opensearch:9200
    jsonData:
      flavor: OpenSearch
      version: 2.11.0
      database: sre-logs
      timeField: "@timestamp"

  - name: OpenSearch Traces
    type: grafana-opensearch-datasource
    uid: opensearch-traces
    access: proxy
    url: http://opensearch:9200
    jsonData:
      flavor: OpenSearch
      version: 2.11.0
      database: sre-traces
      timeField: "startTime"
